### ISSUE TITLE
Help text only appears when the field name matches the data source property name

### ISSUE THREAD

**Issue by EliJDonahue** [ProcessPLM/Aras-Mouse-Over-Help#5]
If the name of a field does not match the name of the data source property, the help text will not be set. See these lines in the code:

```
if (help_text!=="" && prop_name!=="" && getFieldByName(prop_name)!=null){
    getFieldByName(prop_name).title=help_text;
}
```

If you check the id of the data source against the id of the property, instead of the names, this should work more consistently.

**Comment by EliJDonahue** [comment]
@ProcessPLM, can you tag this issue with a tag named "hacktoberfest" so it will be easy for Hacktoberfest participants to find? Thanks!

**Comment by HarshaVR** [comment]
Hi,

I revised the Method '**FRM_SetHelpText**' as shown below. Now, the help text is shown for the field though property name and field name do not match.

```
//Find all properties from ItemType defnition which have help text populated:
var cntxt = document.thisItem;
var q = cntxt.newItem("Property", "get");
q.setAttribute("select", "help_text,name");
q.setProperty("source_id", cntxt.getAttribute("typeId"));
q.setProperty("help_text", "%");
//alert("Form Field Name Query - " + q);
var r = q.apply();
//alert("Form Field Names - " + r);

//Set the 'title' attribute for each field (matches on property name = field name)
//**Update Set the 'title' attribute for each field (matches on property id = field's datasource id)
for (i = 0; i < r.getItemCount(); i++) {
    var itm = r.getItemByIndex(i);
    var help_text = itm.getProperty("help_text", "");
    //var prop_name = itm.getProperty("name", "");

    //Get the field whose datasource id equal to the property id
    var field = cntxt.newItem("Field", "get");
    field.setAttribute("select", "name,propertytype_id");
    field.setProperty("propertytype_id", itm.getID());
    field.setPropertyCondition("propertytype_id", "eq");
    field = field.apply();
    if (field && field.getItemCount() === 1) {
        var field_name = field.getProperty("name", "");
        if (help_text !== "" && field_name !== "" && getFieldByName(field_name) !== null) {
            getFieldByName(field_name).title = help_text;
        }
    }
}
return;



```

**Comment by ProcessPLM** [comment]
Below is an updated version of the method.   I took an approach to hit the server one time for my request of all properties with help text.  Once I had all help text I can perform a match through a loop.  This cuts down on the chatter between the client and the server.

// FRM_SetHelpText - Set Help Text for Mouse Over on Screens
// Set 'title' for all fields on form which have data_source
// properties with specified help_text on the ItemType definition.
// This is a generic method which may be used for the onLoad Event
// handler for any ItemType form.
var cntxt = document.thisItem;
//Find all properties for this ItemType which have help text populated:
var prop = cntxt.newItem("Property","get");
prop.setAttribute("select","help_text");
prop.setProperty("source_id",cntxt.getAttribute("typeId"));
prop.setProperty("help_text","%");
var propList = prop.apply();
var propIDList = "";
var propCount = propList.getItemCount();
//check the count and stop here if there are no properties with help text
if (propCount === 0 ) { return; }
//create an "in" list of IDs so we only get the fields that need help text
for (c = 0; c < propCount; c++){
    var thisProp = propList.getItemByIndex(c);
    propIDList += "\'" + thisProp.getID() + "\',";
}

//get the fields
var field = cntxt.newItem("Field", "get");
field.setAttribute("select", "name, propertytype_id");
field.setPropertyCondition("propertytype_id", "in");
field.setProperty("propertytype_id", propIDList.substring(0, propIDList.length-1));
var results = field.apply();
var fieldCount = results.getItemCount()
for (i=0; i < fieldCount; i++){
    var f = results.getItemByIndex(i);
    var propId = f.getProperty("propertytype_id", "");

    for (c = 0; c < propCount; c++){
        var thisProp = propList.getItemByIndex(c);
        //find a match between the field.propertytype_id and the property.id and fill the element title
        if (thisProp.getProperty("id", "") === propId) {
            getFieldByName(f.getProperty("name")).title = thisProp.getProperty("help_text", "");
        }
    }
}
return;
